### ISSUE TITLE
errors with others transport modes than websockets

### ISSUE THREAD

**Issue by cedricmartel** [slimjack/IWC-SignalR#13]
Hi there, 
I find your project very useful, but i couldn't make it work with non websocket transport mode.
Do you reproduce these problems or am I missing sth ?

``` javascript
SJ.iwc.SignalR.start({ transport: ['longPolling'] })
```

Thanks & regards,

**Comment by slimjack** [comment]
Hi,
I'm currently don't have a time to work on my public projects, but I hope I will continue in a few months.  Regarding your question: I'm using IWC-SignalR only with default config. So, I didn't test it with explicit transport definition. But I tested it in IE9 which doesn't support websockets. Maybe IWC-SignalR has a bug with explicit configuration. Sorry, but I don't have a time for investigation.
Also take into account issues related to IWC. Looks like this mechanism is not reliable. But for now it works ok in my project (I'm using IWC-SignalR just for user popup notifications).

**Comment by cedricmartel** [comment]
Thanks for the feedback and for the highlightbased on iwc issues, that are ok for me since it is also for notification purpose. My problem is for IE9 support that I couldn't work at all. I unfortunately neither have much time, I am planning to make the following hack in a js signalr constructor : 
- forcing websocket use for modern browsers with iwc-signalr
- use native signalr lib for IE < 10, wich will add ie8 support but restrict tab usage
- add specific warning for fallen connections due to tab restrictions
