### ISSUE TITLE
Query string parameters

### ISSUE THREAD

**Issue by ghost** [slimjack/IWC-SignalR#14]
Hi, 

I'm using the library and one requirement is to send a user identifier when connecting. Before the library I was doing something like
$.connection.hub.qs = { id = '123' }

but I don't find how to do it now that I'm using IWC-SignalR. Any ideas about how to achieve this? I'm kind of new with SignalR.

**Comment by ghost** [comment]
I hacked the library. I might upload my changes to make them available for the community.

**Comment by slimjack** [comment]
You are welcome. Please share your work.
