### ISSUE TITLE
Issue on window unload

### ISSUE THREAD

**Issue by jeanie77** [slimjack/IWC-SignalR#15]
I'm using <s>window.onbeforeunload</s> window.onunload function to call a method on web server as the user leaves a page. After referencing IWC-SignalR library, the method doesn't get called anymore. I think this could be a matter of timings, maybe it's the browser that cancels all activities after a given timeout. Probably IWC requires some time to do clean up activities on unload, and when my function gets executed it's too late.
Do you have any suggestion? Is there something I could do to ensure all unload activities gets executed?

**Comment by slimjack** [comment]
@jeanie77 
Neither IWC nor IWC-SignalR doesn't use 'beforeunload' event. 'unload' event is fired after 'beforeunload'. To help you I need more details - how do you subscribe on 'beforeunload' event?

**Comment by jeanie77** [comment]
Sorry for the typo: I was referring to window.onunload event...

**Comment by slimjack** [comment]
Don't understand why this happens. Could you please try to subscribe via `window.addEventListener('unload', ...)`

**Comment by jeanie77** [comment]
Thank you, it solved. As a workaround I used async=false on ajax call, but your suggestion seems cleaner. 
I still don't understand why this is happening...

**Comment by slimjack** [comment]
Be aware that [addEventListener is supported only in IE11](https://caniuse.com/#feat=addeventlistener)

**Comment by jeanie77** [comment]
I'm trying not to depend on unload event, anyway. It's rather unreliable. Thanks for your support :)
