### ISSUE TITLE
How can i reuse this for socket-io

### ISSUE THREAD

**Issue by nelu** [slimjack/IWC-SignalR#16]
Hi, sorry to bother with funny questions. 
The project seems the key ingredient for many websocket solutions today, which lack the "connection reuse" functionality.

I was wondering if its easy to implemented to work with socket-io for example, (autobahn wamp). 
Something more wrapper-like
Right now i found this based on shared webworkers https://github.com/IguMail/socketio-shared-webworker (which is a future solution), but most browsers have issues with web workers.

Using localStorage for intersession comm seems more reliable at this point

**Comment by slimjack** [comment]
@nelu I'm not familiar with socket-io, but for SignalR it was not that complex. localStorage also is not 100 % reliable solution (see issues) . For me it's OK, because in my project IWC and SignalR are not used for critical parts. Hi reliable solution can be implemented based on IndexedDB.

**Comment by nelu** [comment]
this works to some extent... https://gist.github.com/nelu/5b90bb3a5557ecd3a2dc1d4f3e7ab917
