### ISSUE TITLE
Need to reference the signalr/hubs

### ISSUE THREAD

**Issue by Jogai** [slimjack/IWC-SignalR#17]
I create the proxy to signalr myself with 

      var hub = connection.createHubProxy("communicationHub");

This way I can still have all my client side scripts bundled with webpack.
Can I still use this project to share the connection, and how?

**Comment by slimjack** [comment]
IWC-SignalR works on top of SignalR. So, unfortunately, it works only if you get proxy via `SJ.iwc.SignalR.getHubProxy `
