### ISSUE TITLE
Error executing signalr-patch.js

### ISSUE THREAD

**Issue by ampeixoto** [slimjack/IWC-SignalR#3]
I am giving this framework a try to see if it solve my problem of limited connections.

But I'm getting the following error in the signar-patch.js:

`Uncaught TypeError: $.connection.hub.stateChanged is not a function`

This error happens in line:  `$.connection.hub.stateChanged(function (changes) {....`

I've added the following scripts:
iwc-all.js,
iwc-signalr.js,
signalr-patch.js

Am I doing something wrong?

I'm using chrome.

**Comment by slimjack** [comment]
Hello,
I've rechecked _signalr-patch.js_ and it works without exceptions.
Maybe you didn't include auto generated proxies (`<script src="signalr/hubs"></script>`). It should be included before _signalr-patch.js_.

**Comment by ampeixoto** [comment]
Hi,

You are right. This Solved the error. 
I suggest you to put this informations in the Usage section of the project README, just to be clearer.

I have two more questions but I will create new issues for them.

Thanks.

**Comment by slimjack** [comment]
I've added this to Readme
