### ISSUE TITLE
Client methods not being called after closing tab holding the signalR connection

### ISSUE THREAD

**Issue by ampeixoto** [slimjack/IWC-SignalR#4]
Hi,

I have the following situation:
- I am starting the connection by using `SJ.iwc.SignalR.start().done(function(){ //Call Server methods to add this client to a specific SignalR Group, say "MyGroupName" })`
- When I call a client method on the server (ASP.NET MVC), I'm not calling it for all Clients, just the ones that are added to "MyGroupName". Something like this: 

`var hub = GlobalHost.ConnectionManager.GetHubContext("MyHub").Clients.Group("MyGroupName");hub.MyClientMethod();`

So, I'm having the following problem:
- When I close the tab that holds the signalR connection I can see that the current connection is disconnected and a new one is created and assigned to another tab. But my methods to add the client to the group aren't called so my client method will not be called anymore.
- Is this the correct behavior or am I doing something wrong in my code?
- Instead of opening a new connection, is it possible to use the same, just by "switching" that connection to another tab? 

In my debugging process I tried to change the server code to: 
`var hub =GlobalHost.ConnectionManager.GetHubContext("MyHub").Clients.All;...` and with this it works as it should. But this is not what I need.

Can you help me finding a solution for this? I would like to use this framework in my projects.

**Comment by slimjack** [comment]
`SJ.iwc.SignalR.start()` returns a promise and callback passed to `done` is called only once when connection established. So, to make your SignalR connection robust to disconnections/reconnections you should also handle `connected` event (`SJ.iwc.SignalR.on('connected', handlerFn)`).
About reusing of connections, I think that this is impossible.

**Comment by ampeixoto** [comment]
Ok. The `connected` event seems to solve the problem. I put my code that was inside `done` callback inside the `connected` event handler and it is working now.

**Comment by slimjack** [comment]
You should take into account that `connected` event is not fired for already established connections. So, you still need `done` callback. This is actual for pages which are not connection owners.
