### ISSUE TITLE
getState() method return disconected even when it is connected

### ISSUE THREAD

**Issue by ampeixoto** [slimjack/IWC-SignalR#5]
Hi,

When I call `SJ.iwc.SignalR.getState()` from the browser console it returns `4` which means that it is disconnected by this property: `$.connection.connectionState`. But the client are called with no problems so it should return `connected` state.

I put breakpoints in that function here:

`var stateData = JSON.parse(serializedData);`
`if (!SJ.iwc.WindowMonitor.isWindowOpen(stateData.windowId)) {
       state = stateData.state;
 }`

 And I see that stateData is a object like this: `{state: 1, windowId: "60737909-57cc-4bb9-b61f-71c9eac0a0dc"}`. So it seems to be in the correct state, but it is not entering in the `if` statement...

Why this is happening?

**Comment by slimjack** [comment]
It's a bug. There shouldn't be a negation. Thanks.
