### ISSUE TITLE
Help New to SignalR

### ISSUE THREAD

**Issue by wireless90** [slimjack/IWC-SignalR#9]
Hi i have trouble getting it to work. I simply want it to display "Connected", once connection  is established.

<div id="counter" style="font-size:30px;">
    </div>

```
    <script src="Scripts/jquery-1.10.2.js"></script>
    <script src="Scripts/jquery.signalR-2.1.2.js"></script>
    <script src="signalr/hubs"></script>
    <script src="Scripts/iwc-signalr.js"></script>
    <script src="Scripts/signalr-patch.js"></script>

    <script type="text/javascript">
        var hubProxy = SJ.iwc.SignalR.getHubProxy('myHub', {

            client: {
                displayMsg: function(msg)
                {
                    $("#counter").text(msg);
                }
            }
        });

        SJ.iwc.SignalR.start().done(function () {
            hubProxy.server.send("Connected!");
        });
    </script>
```

**Comment by wireless90** [comment]
Uncaught ReferenceError: SJ is not defined(anonymous function) @ signalr-patch.js:6(anonymous function) @ signalr-patch.js:165.
Edit. Which scripts from IWC should i include in my project. Should i include it t the scripts folder?

**Comment by slimjack** [comment]
You should include _iwc-all.js_ (from [IWC](https://github.com/slimjack/IWC) repo) and _signalr-patch.js_ before _iwc-signalr.js_.

**Comment by catazep** [comment]
Hi, I think this info should be added into package description:)

**Comment by slimjack** [comment]
@catazep This is reflected in readme. I'll add an example.

**Comment by vishalsinhvaghela** [comment]
SJ.iwc.SignalR not working .net 5
